# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Regla4.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(646, 533)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(460, 490, 171, 32))
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.DominicanRepublic))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 130, 616, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listSugerencias = QtWidgets.QTreeView(self.layoutWidget)
        self.listSugerencias.setObjectName("listSugerencias")
        self.horizontalLayout.addWidget(self.listSugerencias)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbAdd = QtWidgets.QPushButton(self.layoutWidget)
        self.pbAdd.setObjectName("pbAdd")
        self.verticalLayout.addWidget(self.pbAdd)
        self.pbBuscar = QtWidgets.QPushButton(self.layoutWidget)
        self.pbBuscar.setObjectName("pbBuscar")
        self.verticalLayout.addWidget(self.pbBuscar)
        self.pbRemove = QtWidgets.QPushButton(self.layoutWidget)
        self.pbRemove.setObjectName("pbRemove")
        self.verticalLayout.addWidget(self.pbRemove)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.listCarrito = QtWidgets.QTreeView(self.layoutWidget)
        self.listCarrito.setObjectName("listCarrito")
        self.horizontalLayout.addWidget(self.listCarrito)
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setGeometry(QtCore.QRect(390, 10, 177, 68))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.spnPorcentajeSueldo = QtWidgets.QSpinBox(self.splitter)
        self.spnPorcentajeSueldo.setObjectName("spnPorcentajeSueldo")
        self.lblPresupuesto = QtWidgets.QLabel(self.splitter_2)
        self.lblPresupuesto.setText("")
        self.lblPresupuesto.setObjectName("lblPresupuesto")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setObjectName("label_2")
        self.splitter_3 = QtWidgets.QSplitter(Dialog)
        self.splitter_3.setGeometry(QtCore.QRect(21, 11, 301, 102))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.widget = QtWidgets.QWidget(self.splitter_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.linePalabra = QtWidgets.QLineEdit(self.widget)
        self.linePalabra.setObjectName("linePalabra")
        self.horizontalLayout_3.addWidget(self.linePalabra)
        self.widget1 = QtWidgets.QWidget(self.splitter_3)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.txtAutor = QtWidgets.QLineEdit(self.widget1)
        self.txtAutor.setObjectName("txtAutor")
        self.horizontalLayout_2.addWidget(self.txtAutor)
        self.widget2 = QtWidgets.QWidget(self.splitter_3)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.cbxCategoria = QtWidgets.QComboBox(self.widget2)
        self.cbxCategoria.setObjectName("cbxCategoria")
        self.horizontalLayout_4.addWidget(self.cbxCategoria)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Libros  de X autor con palabras excluidas"))
        self.pbAdd.setText(_translate("Dialog", ">>"))
        self.pbBuscar.setText(_translate("Dialog", "Buscar"))
        self.pbRemove.setText(_translate("Dialog", "<<"))
        self.label_3.setText(_translate("Dialog", "Porciento del sueldo"))
        self.label_2.setText(_translate("Dialog", "Presupuesto:"))
        self.label_4.setText(_translate("Dialog", "Palabra a excluir del titulo"))
        self.label.setText(_translate("Dialog", "Autor"))
        self.label_5.setText(_translate("Dialog", "Categoria"))
