# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PantallaPincipal.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 490)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 431))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.listaComprados = QtWidgets.QListView(self.groupBox)
        self.listaComprados.setGeometry(QtCore.QRect(10, 50, 256, 361))
        self.listaComprados.setObjectName("listaComprados")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 181, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(290, 160, 171, 61))
        self.pushButton.setObjectName("pushButton")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.groupBox)
        self.verticalScrollBar.setGeometry(QtCore.QRect(240, 60, 20, 341))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(290, 50, 221, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 90, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 90, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 230, 171, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 350, 171, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 21))
        self.menubar.setObjectName("menubar")
        self.menuConsultasPredeterminadas = QtWidgets.QMenu(self.menubar)
        self.menuConsultasPredeterminadas.setObjectName("menuConsultasPredeterminadas")
        self.menuConsultasNuevas = QtWidgets.QMenu(self.menubar)
        self.menuConsultasNuevas.setObjectName("menuConsultasNuevas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLibrosRecientesConEntradasExtraRegla1 = QtWidgets.QAction(MainWindow)
        self.actionLibrosRecientesConEntradasExtraRegla1.setObjectName("actionLibrosRecientesConEntradasExtraRegla1")
        self.actionLibrosDeFiccinDe4OMsEstrellasConEntradasExtrasY10DeDescuento = QtWidgets.QAction(MainWindow)
        self.actionLibrosDeFiccinDe4OMsEstrellasConEntradasExtrasY10DeDescuento.setObjectName("actionLibrosDeFiccinDe4OMsEstrellasConEntradasExtrasY10DeDescuento")
        self.actionRegla3 = QtWidgets.QAction(MainWindow)
        self.actionRegla3.setObjectName("actionRegla3")
        self.actionRegla4 = QtWidgets.QAction(MainWindow)
        self.actionRegla4.setObjectName("actionRegla4")
        self.actionRegla5 = QtWidgets.QAction(MainWindow)
        self.actionRegla5.setObjectName("actionRegla5")
        self.menuConsultasPredeterminadas.addAction(self.actionLibrosRecientesConEntradasExtraRegla1)
        self.menuConsultasPredeterminadas.addAction(self.actionLibrosDeFiccinDe4OMsEstrellasConEntradasExtrasY10DeDescuento)
        self.menuConsultasPredeterminadas.addAction(self.actionRegla3)
        self.menuConsultasPredeterminadas.addAction(self.actionRegla4)
        self.menuConsultasPredeterminadas.addAction(self.actionRegla5)
        self.menubar.addAction(self.menuConsultasPredeterminadas.menuAction())
        self.menubar.addAction(self.menuConsultasNuevas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bookeeper"))
        self.label.setText(_translate("MainWindow", "Libros Comprados Recientemente"))
        self.pushButton.setText(_translate("MainWindow", "Nueva busqueda"))
        self.label_2.setText(_translate("MainWindow", "Fondos Actuales"))
        self.pushButton_3.setText(_translate("MainWindow", "Ingresar Fondos"))
        self.pushButton_2.setText(_translate("MainWindow", "Bonos"))
        self.pushButton_4.setText(_translate("MainWindow", "Busqueda Especial"))
        self.pushButton_5.setText(_translate("MainWindow", "Salir"))
        self.menuConsultasPredeterminadas.setTitle(_translate("MainWindow", "Consultas Predeterminadas"))
        self.menuConsultasNuevas.setTitle(_translate("MainWindow", "Consultas nuevas"))
        self.actionLibrosRecientesConEntradasExtraRegla1.setText(_translate("MainWindow", "Libros recientes con entradas extra (Regla #1)"))
        self.actionLibrosDeFiccinDe4OMsEstrellasConEntradasExtrasY10DeDescuento.setText(_translate("MainWindow", "Libros de SciFi 4+ estrellas  10%+Extra (Regla #2)"))
        self.actionRegla3.setText(_translate("MainWindow", "Regla #3"))
        self.actionRegla4.setText(_translate("MainWindow", "Regla #4"))
        self.actionRegla5.setText(_translate("MainWindow", "Regla #5"))
